### ISSUE TITLE
add SpeedLab by BrowserStack

### ISSUE THREAD

**Issue by DanielRuf** [website-checks/website-checks#55]
https://www.browserstack.com/speedlab

Redirects to the report:

https://www.browserstack.com/speedlab/report/d2edb00702086f6c63727753fc5862a5386676e3

Shows this while the report is generated:

<img width="696" alt="Bildschirmfoto 2020-06-11 um 22 22 48" src="https://user-images.githubusercontent.com/827205/84435473-2b1ec300-ac32-11ea-8e3a-7d98fea7bade.png">

**Comment by MyIsaak** [comment]
@DanielRuf I noticed Speedlab asks for a login after the first try. Seems a bit compilcated in this aspect.

**Comment by DanielRuf** [comment]
> @DanielRuf I noticed Speedlab asks for a login after the first try. Seems a bit compilcated in this aspect.

Oh, ok. It seems this is new. So their service / website can not be used to check multiple pages.
<img width="245" alt="Bildschirmfoto 2021-11-17 um 18 31 21" src="https://user-images.githubusercontent.com/827205/142251860-ed85a13d-17c8-426f-a39f-694d9b362429.png">
<img width="400" alt="Bildschirmfoto 2021-11-17 um 18 31 29" src="https://user-images.githubusercontent.com/827205/142251865-60a9a765-d799-4f9e-ae94-4115b9054326.png">

Then I would say, that we do not add speedlab as check.

**Comment by MyIsaak** [comment]
What if someone enters their login details in cli? We can also try a testing account, although one should check the ToC about this.

**Comment by DanielRuf** [comment]
> What if someone enters their login details in cli? We can also try a testing account, although one should check the ToC about this.

That would be an option. Some notiv'ce "sorry, free report not available without login. Please go to ..., read the ToS, signup and provide the login details.


Username: please enter
Password: please enter
"

But this would require new cli features like (password) prompts.
