### ISSUE TITLE
integrate yellow lab tools checker

### ISSUE THREAD

**Issue by MyIsaak** [website-checks/website-checks#63]
With Hacktoberfest going along, I plan to integrate a performance-wise checker (instead of security) in the coming days. Its hosted at `https://yellowlab.tools/` where you can see more about the checks. Interestingly enough this tool is [open-source](https://github.com/YellowLabTools/YellowLabTools). What do you think @DanielRuf ?

**Comment by DanielRuf** [comment]
This looks interesting. It seems we can click on each result and see details. Not sure if there is a long detailed print version or only the dashboard with all single results.

![IMG_20201012_084852](https://user-images.githubusercontent.com/827205/95714102-fcf4d280-0c67-11eb-870f-138ea6b76c3e.jpg)

**Comment by MyIsaak** [comment]
Unfortunately not everything is in one page. My current solution is to output 2 PDFs with numbered titles (i.e. `yellow-lab-1.pdf`, `yellow-lab-2.pdf`). In another issue, one can propose to merge them together with a PDF dependency ([pdf.js](https://github.com/mozilla/pdf.js/), jsPDF or another one).

**Comment by DanielRuf** [comment]
> 2 PDFs with numbered titles

This should be the right approach. I have added the `hacktoberfest` topic to this repository so the PRs should be counted now by default.
