### ISSUE TITLE
tags / releases for the latest versions

### ISSUE THREAD

**Issue by DanielRuf** [website-checks/website-checks#82]
It looks like some tags are not yet in this repo.
You might also want to create the tags and push (`git push --tags`) them so they are linked to the relevant commits.

See https://github.com/website-checks/website-checks/releases/

**Comment by MyIsaak** [comment]
My bad. I'll get onto this.

**Comment by DanielRuf** [comment]
No problem =)

**Comment by MyIsaak** [comment]
Ok. I've added all releases and pubilshed to npm. The latest version is now `v1.20.3`

**Comment by DanielRuf** [comment]
Perfect, closing as resolved.
