### ISSUE TITLE
PageSpeed Insights CI check failed

### ISSUE THREAD

**Issue by MyIsaak** [website-checks/website-checks#84]
![image](https://user-images.githubusercontent.com/4984415/143326940-e4d9343f-7b4a-4948-a9e3-a263f85efd5d.jpeg)

**Comment by DanielRuf** [comment]
Looks like the selector has changed or the page needs longer than 60 seconds (probably not the case). Let me quickly check that.

**Comment by DanielRuf** [comment]
Probably selector has changed:

![grafik](https://user-images.githubusercontent.com/827205/143400836-6006e2a6-0d7d-4082-9020-49f68063b70c.png)

Google has drastically changed the markup and it looks like the best selector(s) are now the two buttons for the mobile and the desktop result:

![grafik](https://user-images.githubusercontent.com/827205/143401104-ad458b5e-1bbe-4f48-a1f2-179b9a27dacc.png)

**Comment by DanielRuf** [comment]
This is also new (shows more detailed data):

![grafik](https://user-images.githubusercontent.com/827205/143401210-ed5e9993-2611-43ef-8e06-6a2adb8c853b.png)

**Comment by MyIsaak** [comment]
I'll get onto this.
